title: "Мой Простой Магазин"
description: "Тестовый магазин на Jekyll и CSV"
baseurl: "/simple-shop"
url: "https://serhii50.github.io"
theme: minima
plugins:
  - jekyll-seo-tag

# Настройка генерации
page_gen:
  - data: 'products'
    template: 'product'
    name: 'id'
    dir: 'product'
    extension: 'html'
