title: "Мой Простой Магазин"
description: "Тестовый магазин на Jekyll и CSV"
url: "https://serhii50.github.io"
baseurl: "/simple-shop"
theme: minima

plugins:
  - jekyll-seo-tag

# Настройки генератора страниц
page_gen:
  - data: 'products'
    template: 'product'
    name: 'id'
    dir: 'product'
    extension: 'html'
