title: "Мой Простой Магазин"
description: "Тестовый магазин на Jekyll и CSV"
baseurl: "/simple-shop"
url: "https://serhii50.github.io"
theme: minima
plugins:
  - jekyll-seo-tag

# Настройка генерации
page_gen:
  - data: 'products'       # Имя файла в папке _data (products.csv)
    template: 'product'    # Имя шаблона в папке _layouts (product.html)
    name: 'id'             # Колонка в CSV, которая станет именем файла (1.html, 2.html)
    dir: 'product'         # Папка, куда сложить готовые страницы
    extension: 'html'
